名称: Jekyll 站点 CI

on:
  push:
分支: [ "main" ]
 拉取请求:
分支: [ "main" ]

作业:
构建:

运行平台: ubuntu-latest

步骤:
    - 使用: actions/checkout@v4
    - 名称: 在 jekyll/builder 容器中构建站点
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
